[package]
name = "companion"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["net", "macros", "rt-multi-thread", "io-util", "fs", "sync"] }
tracing = "0.1"
tracing-subscriber = "0.3"
libc = "0.2"

[profile.release]
opt-level = "s"
lto = true
strip = true
panic = "abort"